Need to be a int not a float
if not TypeError:
  File "/home/sylvain/Téléchargements/src/TaskCoach-future-renouveau/taskcoach/taskcoachlib/domain/attribute/font/mixer.py", line 35, in mix
    return wx.Font(pointSize, family, style, weight, underline=underlined)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Font(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'